name: Install Python
on: 
  push:
    branches:
      - main
jobs:
  check-python-version
    runs-on: ubantu-latest
    steps:
      - uses: action/checkout@v2
      - name: set up Python 3.6.9
      uses: action/setup-python@v2
      with:
        python-version: 3.6.9
     - name: Check Version
       run: python --version
